### PR TITLE
Fix engine changed even if user aborts install request

### LINKED ISSUE #262: Engine switched even if user enters no
### Bug description

When `use-engine` prompts the user for confirmation before downloading reuqired components, if the user enters no, engine is changed anyway

### To reproduce

```
sudo gemma3 use-engine cpu
sudo gemma3 prune-cache --engine=amd-gpu
sudo gemma3 use-engine amd-gpu
```
Enter `n` when prompted
Check that engine has been changed anyway
```
$ sudo gemma3 use-engine cpu
Engine changed to "cpu".

Run "snap restart gemma3.server" to use the new engine.
$ sudo gemma3 prune-cache --engine=amd-gpu
Removing components:
Warning: unable to get component sizes: error finding components of current snap: not installed from store
- llamacpp-rocm

Continue pruning "amd-gpu" engine? [y/n] y
sudo gemma3 use-engine amd-gpu
Warning: unable to get component sizes: error finding components of current snap: not installed from store
Need to install the following components:
- llamacpp-rocm

Do you want to continue? [y/n] n
Exiting. No changes applied.
Engine changed to "amd-gpu".

Run "snap restart gemma3.server" to use the new engine.
$ sudo gemma3 list-engines
ENGINE            VENDOR             DESCRIPTION                         COMPAT
amd-gpu*          Canonical Ltd      Use ROCm for inference on AMD GPUs. devel 
cpu-xsmall        Canonical Ltd      Use CPU, very low footprints. Tex…  yes   
cpu               Canonical Ltd      Use CPU with a good balance betwe…  yes   
nvidia-gpu-arm64  Canonical Ltd      Use CUDA for inference on Nvidia …  no    
nvidia-gpu-amd64  Canonical Ltd      Use CUDA for inference on Nvidia …  no    
intel-gpu         Intel Corporation  Use Intel integrated and discrete…  no    
intel-cpu         Intel Corporation  Use Intel CPUs                      no


### Snap version

```shell
snap          2.74.1
snapd         2.74.1
series        16
ubuntu        24.04
kernel        6.17.0-1012-oem
architecture  amd64


```

### System information

<details>

```yaml
Ubuntu 24.04
```

</details>

### PR DESCRIPTION
**Pull request by mrmara**
fixes https://github.com/canonical/inference-snaps/issues/262

```
$ sudo gemma3 use-engine amd-gpu 

Engine changed to "amd-gpu".

Run "snap restart gemma3.server" to use the new engine.
```

```
$ sudo gemma3 prune-cache --engine=cpu
Removing components:
Warning: unable to get component sizes: error finding components of current snap: not installed from store
- llamacpp

Continue pruning "cpu" engine? [y/n] y
```

```
$ sudo gemma3 use-engine cpu
Warning: unable to get component sizes: error finding components of current snap: not installed from store
Need to install the following components:
- llamacpp

Do you want to continue? [y/n] n
Exiting. No changes applied.
```

```
$ sudo gemma3 list-engines
ENGINE            VENDOR             DESCRIPTION                         COMPAT
amd-gpu*          Canonical Ltd      Use ROCm for inference on AMD GPUs. devel 
cpu-xsmall        Canonical Ltd      Use CPU, very low footprints. Tex…  yes   
cpu               Canonical Ltd      Use CPU with a good balance betwe…  yes   
nvidia-gpu-arm64  Canonical Ltd      Use CUDA for inference on Nvidia …  no    
nvidia-gpu-amd64  Canonical Ltd      Use CUDA for inference on Nvidia …  no    
intel-gpu         Intel Corporation  Use Intel integrated and discrete…  no    
intel-cpu         Intel Corporation  Use Intel CPUs                      no
```

### CODE REVIEW

File: cmd/cli/commands/use-engine.go [hunk 1]
```diff
@@ -308,7 +312,7 @@ func (cmd *useEngineCommand) installMissingComponents(engine *engines.Manifest)
 		return false, fmt.Errorf("error checking installed components: %v", err)
 	}
 	if len(missingComponents) == 0 {
-		return false, nil
+		return true, nil
```
Comment (farshidtz) [inline cmd/cli/commands/use-engine.go]: The fix is good, but this is misleading. "Installed" is true if no components are missing and nothing has been installed.

My suggestion is to change "installed" to "cancelledByUser", leave it to false (default value), and set it to true only if the user doesn't agree to install.

**Review by farshidtz — CHANGES_REQUESTED** [review]

File: cmd/cli/commands/use-engine.go (hunk 1 above)
Comment (farshidtz) [reply cmd/cli/commands/use-engine.go]: Also, consider replacing `Exiting. No changes applied.` with `Cancelled. No changes applied.`

File: cmd/cli/commands/use-engine.go [hunk 2]
```diff
@@ -183,7 +182,7 @@ func (cmd *useEngineCommand) switchEngine(engineName string) error {
 		return fmt.Errorf("error setting new engine configurations: %v", err)
 	}
 
-	fmt.Printf("Engine changed to %q.\n", engineName)
+	fmt.Printf("\nEngine changed to %q.\n", engineName)
```
Comment (farshidtz) [inline cmd/cli/commands/use-engine.go]: Let's drop the line break before Engine changed altogether:
```suggestion
	fmt.Printf("Engine changed to %q.\n", engineName)
```

It is adding an unwanted space when no components are installed:
```console
$ sudo stack-utils use-engine intel-cpu
Need to install the following components:
- dummy-component-1 (16.0KiB)

Do you want to continue? [y/n] n
Cancelled. No changes applied.
$ sudo stack-utils use-engine intel-cpu
Need to install the following components:
- dummy-component-1 (16.0KiB)

Do you want to continue? [y/n] y

Installed dummy-component-1

Engine changed to "intel-cpu".

Run "snap restart stack-utils.server" to use the new engine.
$ sudo stack-utils use-engine ampere
                                                                     <--------- here
Engine changed to "ampere".

Run "snap restart stack-utils.server" to use the new engine.
```

**Review by farshidtz — APPROVED** [review]
Thanks for the fix.
